# NumPy Operations

* Arrays x Arrays
* Arrays x Scalars
* Universal Array Functions

In [1]:
import numpy as np

In [14]:
A = np.arange(0, 11)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
A + A # addition element wise

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [16]:
A - A # subtraction element wise

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
A * A # subtraction element wise

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [18]:
A + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [19]:
A - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [20]:
A * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [21]:
A / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ])

In [25]:
1 / 0 # Python correctly raises an error when we try a division by zero

ZeroDivisionError: division by zero

In [32]:
A / A # NumPy raises a warning and returns "nan" as a result for zero divided by zero

C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [36]:
1 / A # NumPy raises a warning and returns "inf" as a result of any number divided by zero


C:\ProgramData\Anaconda3\envs\py36\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [38]:
A ** 3 # exponents

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

### Universal Array Functions