# NumPy Array Indexing

In [1]:
import numpy as np

In [3]:
A = np.arange(0,21)

In [4]:
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

### Slice arrays like lists

In [19]:
A[8:15] # slice a portion of an array

array([ 8,  9, 10, 11, 12, 13, 14])

In [21]:
A[:8] # first 8

array([0, 1, 2, 3, 4, 5, 6, 7])

### Broadcasting in Arrays (pay special attention when using slices)

In [52]:
B = A # B is not a copy of A. B is a reference pointing to the same object that A is pointing to in memory.
B[0:4] += 100
B

array([3000, 3001, 3002, 3003,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20])

In [53]:
A

array([3000, 3001, 3002, 3003,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20])

In [54]:
C = A.copy() # C is a copy of A. They are references to different objects in memory

In [57]:
C[0:4] += 50
C

array([3100, 3101, 3102, 3103,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20])

In [58]:
A

array([3000, 3001, 3002, 3003,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20])

### Indexing a 2D Array (matrix)

In [62]:
D = np.array( [ [2,4,6] , [8,10,12] , [14,16,18] ] )

In [63]:
D

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [70]:
D[1][1]# slicing matrices using double bracket notation

10

In [71]:
D[1,1]# slicing matrices usgin single bracket with a comma notation

10

### Subsetting matrices

In [76]:
D[:1,:]

array([[2, 4, 6]])

In [75]:
D[:,:1]

array([[ 2],
       [ 8],
       [14]])

In [72]:
D[:2,:2]

array([[ 2,  4],
       [ 8, 10]])

### Conditional Selection

In [78]:
E = np.arange(0,16)
E

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [111]:
boolean_conditional_array = E > 5

In [113]:
boolean_conditional_array

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [114]:
E[boolean_conditional_array]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [109]:
(E % 2 == 1).mean()
(E[1:] > 10).mean()


0.3333333333333333

In [116]:
F = np.arange(50).reshape(5,10)
F


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [125]:
F[ 1:3, : ]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [126]:
F[ : , 3:5 ]

array([[ 3,  4],
       [13, 14],
       [23, 24],
       [33, 34],
       [43, 44]])

In [118]:
F[1:3, 3:5]

array([[13, 14],
       [23, 24]])