# Intro NumPy

_"NumPy is a linear algebra library that is used by many other Python libraries in the PyData Ecosystem."_

## NumPy Arrays

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
np.array(my_mat) # casts a list into an array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# this is similar to Python built in range() function
# np.arange([start,] stop[, step,], dtype=None)
np.arange(0, 21, 2) # creates an array based on a range and a step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np.zeros(10) # creates a vector with 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros( (3,4) ) # creates a matrix with (l,c) l lines and c columns

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones( (2,3) ) # creates a matrix of ones with 2 lines and 3 columns

array([[1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)
np.linspace( 0, 5, 10 ) # return evenly spaced numbers over a specified interval

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [12]:
np.identity(4) # creates an identity matrix of order 4 ( np.identity() calls np.eye() )

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.eye(5, k=1) # can create identity matrices with the diagonal offsetted

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

### Generating Matrices of Random Numbers

In [14]:
np.random.rand(5)

array([0.65343903, 0.47369844, 0.48183449, 0.43738269, 0.84557751])

In [15]:
np.random.randn(5)

array([-1.85194337, -2.12349497,  1.08516622,  0.90541232,  0.01437075])

In [16]:
np.random.randint(1, 61, 6)

array([ 7, 43,  4, 27, 40, 47])

### Useful matrices attributes and methods

In [41]:
A = np.arange(6)

In [42]:
A

array([0, 1, 2, 3, 4, 5])

In [43]:
B_randArray = np.random.randint(0,10,6)

In [44]:
B_randArray

array([2, 7, 5, 9, 4, 8])

### Reshape

In [47]:
 A.reshape(2,3) # reshape requires l times c to be equals len(A)

array([[0, 1, 2],
       [3, 4, 5]])

### Min, Max and Index location

In [48]:
B_randArray.max()

9

In [49]:
B_randArray.min()

2

In [51]:
B_randArray.argmax() # returns the maximum's element index location

3

In [52]:
B_randArray.argmin() # returns the minimum's element index location


0

In [55]:
B_randArray.shape

(6,)

###  Matrix Data Type

In [56]:
A.dtype

dtype('int32')

In [59]:

from numpy.random import randint

randint( 2, 10 )


6